In [1]:
import pandas

In [2]:
dataset = pandas.read_csv('titanic.csv')

In [3]:
dataset.head() # Exibir as primeiras linhas do dataset para ter uma visão geral dos dados

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [4]:
dataset.isna().sum() # Verificar a quantidade de valores ausentes em cada coluna

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [5]:
dataset.dtypes # Verificar os tipos de dados de cada coluna

pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

In [6]:
dataset.info() # Obter informações gerais sobre o dataset, incluindo o número de entradas, colunas, tipos de dados e memória utilizada

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

In [7]:
dataset.columns # Listar os nomes das colunas do dataset

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='str')

In [8]:
dataset['ticket'] # Acessar a coluna 'ticket' do dataset, que contém os números dos bilhetes dos passageiros

0        24160
1       113781
2       113781
3       113781
4       113781
         ...
1304      2665
1305      2665
1306      2656
1307      2670
1308    315082
Name: ticket, Length: 1309, dtype: str

In [9]:
dataset['name'].str.upper() # Converter os nomes dos passageiros para letras maiúsculas

0                         ALLEN, MISS. ELISABETH WALTON
1                        ALLISON, MASTER. HUDSON TREVOR
2                          ALLISON, MISS. HELEN LORAINE
3                  ALLISON, MR. HUDSON JOSHUA CREIGHTON
4       ALLISON, MRS. HUDSON J C (BESSIE WALDO DANIELS)
                             ...
1304                               ZABOUR, MISS. HILENI
1305                              ZABOUR, MISS. THAMINE
1306                          ZAKARIAN, MR. MAPRIEDEDER
1307                                ZAKARIAN, MR. ORTIN
1308                                 ZIMMERMAN, MR. LEO
Name: name, Length: 1309, dtype: str

In [10]:
dataset['name'].str.lower() # Converter os nomes dos passageiros para letras minúsculas

0                         allen, miss. elisabeth walton
1                        allison, master. hudson trevor
2                          allison, miss. helen loraine
3                  allison, mr. hudson joshua creighton
4       allison, mrs. hudson j c (bessie waldo daniels)
                             ...
1304                               zabour, miss. hileni
1305                              zabour, miss. thamine
1306                          zakarian, mr. mapriededer
1307                                zakarian, mr. ortin
1308                                 zimmerman, mr. leo
Name: name, Length: 1309, dtype: str

In [11]:
dataset['name'].str.contains('Miss') # Verificar se o nome do passageiro contém a string 'Miss'

0        True
1       False
2        True
3       False
4       False
        ...
1304     True
1305     True
1306    False
1307    False
1308    False
Name: name, Length: 1309, dtype: bool

In [12]:
dataset['name'].str.startswith('A') # Verificar se o nome do passageiro começa com a letra 'A'

0        True
1        True
2        True
3        True
4        True
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Name: name, Length: 1309, dtype: bool

In [13]:
dataset['name'].str.endswith('E') # Verificar se o nome do passageiro termina com a string 'E'

0       False
1       False
2       False
3       False
4       False
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Name: name, Length: 1309, dtype: bool

In [14]:
dataset['name'].str.contains('Miss').value_counts() # Contar quantos passageiros têm 'Miss' em seus nomes e quantos não têm

name
False    1049
True      260
Name: count, dtype: int64

In [15]:
# title = dataset['name'].str.extract(r', (\w+\.)', expand = False)
dataset['title'] = dataset['name'].str.extract(r', (\w+\.)', expand = False) # Extrair o título dos passageiros a partir da coluna 'name' usando uma expressão regular e criar uma nova coluna 'title' para armazenar os títulos extraídos

In [16]:
dataset['title']

0         Miss.
1       Master.
2         Miss.
3           Mr.
4          Mrs.
         ...
1304      Miss.
1305      Miss.
1306        Mr.
1307        Mr.
1308        Mr.
Name: title, Length: 1309, dtype: str

In [17]:
dataset['title'].value_counts()

title
Mr.          757
Miss.        260
Mrs.         197
Master.       61
Dr.            8
Rev.           8
Col.           4
Major.         2
Mlle.          2
Ms.            2
Mme.           1
Capt.          1
Lady.          1
Sir.           1
Dona.          1
Jonkheer.      1
Don.           1
Name: count, dtype: int64

In [18]:
dataset[dataset['title'].isin(['Capt.', 'Major.'])] # Filtrar os passageiros cujo título é 'Capt.' ou 'Major.' e exibir suas informações

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,title
45,1,0,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.55,B38,S,NaN,NaN,"Washington, DC",Major.
81,1,0,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.00,B22,S,NaN,269.0,"Milwaukee, WI",Capt.
231,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.50,C104,S,6,NaN,"Toronto, ON",Major.