In [3]:
import pandas
import numpy

In [ ]:
elections = pandas.read_csv('data/elections.csv')

In [5]:
print(elections.columns)

Index(['Year', 'Candidate', 'Party', 'Popular vote', 'Result', '%'], dtype='str')

In [6]:
elections.iloc[0, 1]

'Andrew Jackson'

In [7]:
elections[((elections['Year'] == 2024) | (elections['Year'] == 2020))]

     Year       Candidate              Party  Popular vote Result          %
178  2020    Joseph Biden         Democratic      81268924    win  51.311515
179  2020    Donald Trump         Republican      74216154   loss  46.858542
180  2020    Jo Jorgensen        Libertarian       1865724   loss   1.177979
181  2020  Howard Hawkins              Green        405035   loss   0.255731
182  2024    Donald Trump         Republican      77303568    win  49.808629
183  2024   Kamala Harris         Democratic      75019230   loss  48.336772
184  2024      Jill Stein              Green        861155   loss   0.554864
185  2024  Robert Kennedy        Independent        756383   loss   0.487357
186  2024    Chase Oliver  Libertarian Party        650130   loss   0.418895

In [8]:
elections.groupby('Candidate').agg('max')
# Agrupa por candidato e mostra o ano mais recente e o partido mais recente de cada um

                        Year        Party  Popular vote Result          %
Candidate
Aaron S. Watkins        1920  Prohibition        188787   loss   0.708351
Abraham Lincoln         1864   Republican       2211317    win  54.951512
Adlai Stevenson         1956   Democratic      27375090   loss  44.446312
Al Gore                 2000   Democratic      50999897   loss  48.491813
Al Smith                1928   Democratic      15015464   loss  40.902853
...                      ...          ...           ...    ...        ...
William Z. Foster       1932    Communist        103307   loss   0.261069
Winfield Scott          1852         Whig       1386942   loss  44.056548
Winfield Scott Hancock  1880   Democratic       4444976   loss  48.278422
Woodrow Wilson          1916   Democratic       9126868    win  49.367987
Zachary Taylor          1848         Whig       1360235    win  47.309296

[135 rows x 5 columns]

In [9]:
elections[['Candidate', 'Year', 'Party']].groupby('Candidate').agg('max')
# Agrupa por candidato e mostra o ano mais recente e o partido mais recente de cada um, mas só mostra as colunas de candidato, ano e partido

                        Year        Party
Candidate
Aaron S. Watkins        1920  Prohibition
Abraham Lincoln         1864   Republican
Adlai Stevenson         1956   Democratic
Al Gore                 2000   Democratic
Al Smith                1928   Democratic
...                      ...          ...
William Z. Foster       1932    Communist
Winfield Scott          1852         Whig
Winfield Scott Hancock  1880   Democratic
Woodrow Wilson          1916   Democratic
Zachary Taylor          1848         Whig

[135 rows x 2 columns]

In [10]:
elections.groupby('Candidate').count()
# Quantidade de vezez que cada candidato apareceu

                        Year  Party  Popular vote  Result  %
Candidate
Aaron S. Watkins           1      1             1       1  1
Abraham Lincoln            2      2             2       2  2
Adlai Stevenson            2      2             2       2  2
Al Gore                    1      1             1       1  1
Al Smith                   1      1             1       1  1
...                      ...    ...           ...     ... ..
William Z. Foster          1      1             1       1  1
Winfield Scott             1      1             1       1  1
Winfield Scott Hancock     1      1             1       1  1
Woodrow Wilson             2      2             2       2  2
Zachary Taylor             1      1             1       1  1

[135 rows x 5 columns]

In [11]:
elections.groupby('Candidate').value_counts()
# Mostra os dados agruoados por candidato e por ano, partido, etc

Candidate               Year  Party           Popular vote  Result  %
Aaron S. Watkins        1920  Prohibition     188787        loss    0.708351     1
Abraham Lincoln         1860  Republican      1855993       win     39.699408    1
                        1864  National Union  2211317       win     54.951512    1
Adlai Stevenson         1956  Democratic      26028028      loss    42.174464    1
                        1952  Democratic      27375090      loss    44.446312    1
                                                                                ..
Winfield Scott          1852  Whig            1386942       loss    44.056548    1
Winfield Scott Hancock  1880  Democratic      4444976       loss    48.278422    1
Woodrow Wilson          1916  Democratic      9126868       win     49.367987    1
                        1912  Democratic      6296284       win     41.933422    1
Zachary Taylor          1848  Whig            1360235       win     47.309296    1
Name: count, Length: 187, dtype: int64

In [12]:
elections.groupby('Year').filter(lambda x: x['%'].max() > 45)
# Filtra os anos em que algum candidato teve mais de 45% dos votos

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
182,2024,Donald Trump,Republican,77303568,win,49.808629
183,2024,Kamala Harris,Democratic,75019230,loss,48.336772
184,2024,Jill Stein,Green,861155,loss,0.554864
185,2024,Robert Kennedy,Independent,756383,loss,0.487357
186,2024,Chase Oliver,Libertarian Party,650130,loss,0.418895

In [13]:
elections.groupby('Year').filter(lambda x: x['%'].max() > 45)
# Filtra os anos em que algum candidato teve mais de 45% dos votos, mas só mostra os dados desses anos

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
182,2024,Donald Trump,Republican,77303568,win,49.808629
183,2024,Kamala Harris,Democratic,75019230,loss,48.336772
184,2024,Jill Stein,Green,861155,loss,0.554864
185,2024,Robert Kennedy,Independent,756383,loss,0.487357
186,2024,Chase Oliver,Libertarian Party,650130,loss,0.418895

In [14]:
elections.sort_values('%', ascending=False)
# Ordena os dados por porcentagem de votos, do maior para o menor

     Year           Candidate         Party  Popular vote Result          %
114  1964      Lyndon Johnson    Democratic      43127041    win  61.344703
91   1936  Franklin Roosevelt    Democratic      27752648    win  60.978107
120  1972       Richard Nixon    Republican      47168710    win  60.907806
79   1920      Warren Harding    Republican      16144093    win  60.574501
133  1984       Ronald Reagan    Republican      54455472    win  59.023326
..    ...                 ...           ...           ...    ...        ...
165  2008    Cynthia McKinney         Green        161797   loss   0.123442
148  1996        John Hagelin   Natural Law        113670   loss   0.118219
160  2004    Michael Peroutka  Constitution        143630   loss   0.117542
141  1992            Bo Gritz      Populist        106152   loss   0.101918
156  2004          David Cobb         Green        119859   loss   0.098088

[187 rows x 6 columns]

In [15]:
elections.sort_values('%', ascending=False).groupby('Party').first()
# Mostra o partido mais votado de cada partido, ou seja, o candidato mais votado de cada partido

,Year,Candidate,Popular vote,Result,%
Party,,,,,
American,1856,Millard Fillmore,873053,loss,21.554001
American Independent,1968,George Wallace,9901118,loss,13.571218
Anti-Masonic,1832,William Wirt,100715,loss,7.821583
Anti-Monopoly,1884,Benjamin Butler,134294,loss,1.335838
Citizens,1980,Barry Commoner,233052,loss,0.270182
Communist,1932,William Z. Foster,103307,loss,0.261069
Constitution,2008,Chuck Baldwin,199750,loss,0.152398
Constitutional Union,1860,John Bell,590901,loss,12.639283
Democratic,1964,Lyndon Johnson,43127041,win,61.344703
Democratic-Republican,1824,Andrew Jackson,151271,loss,57.210122
Dixiecrat,1948,Strom Thurmond,1175930,loss,2.412304
Farmer–Labor,1920,Parley P. Christensen,265398,loss,0.995804
Free Soil,1848,Martin Van Buren,291501,loss,10.138474
Green,2000,Ralph Nader,2882955,loss,2.741176
Greenback,1880,James B. Weaver,308649,loss,3.352344
Independent,1992,Ross Perot,19743821,loss,18.956298
Liberal Republican,1872,Horace Greeley,2834761,loss,44.071406
Libertarian,2016,Gary Johnson,4489235,loss,3.307714
Libertarian Party,2024,Chase Oliver,650130,loss,0.418895
National Democratic,1896,John M. Palmer,134645,loss,0.969566
National Republican,1828,John Quincy Adams,500897,loss,43.796073
National Union,1864,Abraham Lincoln,2211317,win,54.951512
Natural Law,1996,John Hagelin,113670,loss,0.118219
New Alliance,1988,Lenora Fulani,217221,loss,0.237804
Northern Democratic,1860,Stephen A. Douglas,1380202,loss,29.522311
Populist,1892,James B. Weaver,1041028,loss,8.645038
Progressive,1912,Theodore Roosevelt,4122721,loss,27.457433
Prohibition,1892,John Bidwell,270879,loss,2.249468
Reform,1996,Ross Perot,8085294,loss,8.408844
Republican,1972,Richard Nixon,47168710,win,60.907806
Socialist,1912,Eugene V. Debs,901551,loss,6.004354
Southern Democratic,1860,John C. Breckinridge,848019,loss,18.138998
States' Rights,1956,T. Coleman Andrews,107929,loss,0.174883
Taxpayers,1996,Howard Phillips,184656,loss,0.192045
Union,1936,William Lemke,892378,loss,1.960733
Union Labor,1888,Alson Streeter,146602,loss,1.288861
Whig,1840,William Henry Harrison,1275583,win,53.051213

In [20]:
elections[['Candidate', 'Party']].groupby('Party').agg('count').sort_values('Candidate', ascending=False).head(5)
# Mostra a quantidade de candidatos de cada partido, ordenado do maior para o menor, e mostra só os 5 primeiros

             Candidate
Party
Democratic          48
Republican          42
Libertarian         12
Prohibition         11
Socialist           10