In [33]:
import pandas
import numpy

In [34]:
babynames = pandas.read_csv('data/babynames.txt', names = ['State', 'Sex', 'Year', 'Name', 'Count'])

In [35]:
babynames.head()

  State Sex  Year      Name  Count
0    CA   F  1910      Mary    295
1    CA   F  1910     Helen    239
2    CA   F  1910   Dorothy    220
3    CA   F  1910  Margaret    163
4    CA   F  1910   Frances    134

In [36]:
babynames[(babynames['Name'] == 'Bella') | (babynames['Name'] == 'Alex') | (babynames['Name'] == 'Narges') | (babynames['Name'] == 'Lisa')]

       State Sex  Year   Name  Count
6289      CA   F  1923  Bella      5
7512      CA   F  1925  Bella      8
12368     CA   F  1932   Lisa      5
14741     CA   F  1936   Lisa      8
17084     CA   F  1939   Lisa      5
...      ...  ..   ...    ...    ...
393248    CA   M  2018   Alex    495
396111    CA   M  2019   Alex    438
398983    CA   M  2020   Alex    379
401788    CA   M  2021   Alex    333
404663    CA   M  2022   Alex    344

[317 rows x 5 columns]

In [37]:
babynames[babynames['Name'].isin(['Bella', 'Alex', 'Narges', 'Lisa'])]

       State Sex  Year   Name  Count
6289      CA   F  1923  Bella      5
7512      CA   F  1925  Bella      8
12368     CA   F  1932   Lisa      5
14741     CA   F  1936   Lisa      8
17084     CA   F  1939   Lisa      5
...      ...  ..   ...    ...    ...
393248    CA   M  2018   Alex    495
396111    CA   M  2019   Alex    438
398983    CA   M  2020   Alex    379
401788    CA   M  2021   Alex    333
404663    CA   M  2022   Alex    344

[317 rows x 5 columns]

In [38]:
babynames[babynames['Name'].str.startswith('N')]

       State Sex  Year    Name  Count
76        CA   F  1910   Norma     23
83        CA   F  1910  Nellie     20
127       CA   F  1910    Nina     11
198       CA   F  1910    Nora      6
310       CA   F  1911  Nellie     23
...      ...  ..   ...     ...    ...
407319    CA   M  2022   Nilan      5
407320    CA   M  2022   Niles      5
407321    CA   M  2022   Nolen      5
407322    CA   M  2022  Noriel      5
407323    CA   M  2022  Norris      5

[12229 rows x 5 columns]

In [39]:
babynames.index

RangeIndex(start=0, stop=407428, step=1)

In [40]:
babynames.set_index('Name').index

Index(['Mary', 'Helen', 'Dorothy', 'Margaret', 'Frances', 'Ruth', 'Evelyn',
       'Alice', 'Virginia', 'Elizabeth',
       ...
       'Zach', 'Zadkiel', 'Zae', 'Zai', 'Zay', 'Zayvier', 'Zia', 'Zora',
       'Zuriel', 'Zylo'],
      dtype='str', name='Name', length=407428)

In [41]:
babynames.columns

Index(['State', 'Sex', 'Year', 'Name', 'Count'], dtype='str')

In [42]:
babynames.shape

(407428, 5)

In [43]:
babynames.size

2037140

In [44]:
babynames.describe()

                Year          Count
count  407428.000000  407428.000000
mean     1985.733609      79.543456
std        27.007660     293.698654
min      1910.000000       5.000000
25%      1969.000000       7.000000
50%      1992.000000      13.000000
75%      2008.000000      38.000000
max      2022.000000    8260.000000

In [45]:
babynames['Sex'].describe()

count     407428
unique         2
top            F
freq      239537
Name: Sex, dtype: object

In [46]:
babynames.sample(5).iloc[:, 2:]

        Year       Name  Count
19816   1943       Lucy     71
238661  2022    Talulah      7
170844  2005     Kaylei      9
353216  2004  Zachariah     51
193060  2010    Bellina      5

In [47]:
babynames[:10].sample(4, replace = True)

  State Sex  Year       Name  Count
7    CA   F  1910      Alice    118
9    CA   F  1910  Elizabeth     93
3    CA   F  1910   Margaret    163
2    CA   F  1910    Dorothy    220

In [48]:
babynames[babynames['Year'] == 2000].sample(4, replace = True).iloc[:, 2:]

        Year      Name  Count
151805  2000     Leigh      7
344110  2000  Natanael      8
150070  2000     Mindy     29
343471  2000    Niklas     16

In [49]:
babynames['Sex'].value_counts()

Sex
F    239537
M    167891
Name: count, dtype: int64

In [50]:
babynames['Name'].unique()

<StringArray>
[     'Mary',     'Helen',   'Dorothy',  'Margaret',   'Frances',      'Ruth',
    'Evelyn',     'Alice',  'Virginia', 'Elizabeth',
 ...
      'Wael',     'Woods',      'Xane',       'Xen',   'Yadriel',  'Yeferson',
    'Yosiah',       'Zae',       'Zai',   'Zayvier']
Length: 20437, dtype: str

## Adicionando, removendo e modificando colunas

Para adicionar um coluna, use `[]` para referenciar a nova coluna desejada e, em seguida, atribua a ela uma `Series` ou um vetor com o comprimento apropriado.

In [51]:
# crie uma Series com o comprimento de cada nome
babyname_lengths = babynames['Name'].str.len()

# adiciona um Series como um coluna chamada 'name_lengths'
babynames['name_lengths'] = babyname_lengths

Para modificar uma coluna, use `[]` - ou `.loc[]`- para acessar a coluna desejada e, em seguida, atribua-a novamente a um novo vetor ou Series.

In [52]:
# modifique a coluna 'name_lengths' para que seja uma unidade menor do que seu valor original
babynames['name_lengths'] = babynames['name_lengths'] - 1

Para renomear uma coluna, use `.rename()`

In [53]:
babynames = babynames.rename(columns = {'name_lengths' : 'Length'})

Para remover uma coluna, use `.drop`

In [54]:
babynames = babynames.drop('Length', axis = 'columns')

## Ordenação

In [55]:
babynames.sort_values('Count')

       State Sex  Year      Name  Count
407424    CA   M  2022       Zia      5
407409    CA   M  2022  Yeferson      5
407378    CA   M  2022    Taylen      5
407410    CA   M  2022  Yehoshua      5
407411    CA   M  2022     Yeray      5
...      ...  ..   ...       ...    ...
283146    CA   M  1970   Michael   8196
281850    CA   M  1969   Michael   8245
317387    CA   M  1990   Michael   8246
267017    CA   M  1956   Michael   8258
268041    CA   M  1957   Michael   8260

[407428 rows x 5 columns]

In [56]:
babynames['Name'].sort_values()

366001      Aadan
384005      Aadan
369120      Aadan
398211    Aadarsh
370306      Aaden
           ...
220691      Zyrah
197529      Zyrah
217429      Zyrah
232167      Zyrah
404544      Zyrus
Name: Name, Length: 407428, dtype: str

#### Criar uma coluna temporária

In [57]:
babyname_lengths = babynames['Name'].str.len()

babynames['name_lengths'] = babyname_lengths

babynames = babynames.sort_values(by = 'name_lengths', ascending = False)

babynames = babynames.drop('name_lengths', axis = 'columns')

babynames.head()

       State Sex  Year             Name  Count
316886    CA   M  1989  Franciscojavier      6
327472    CA   M  1993  Ryanchristopher      5
337477    CA   M  1997  Ryanchristopher      5
321792    CA   M  1991  Ryanchristopher      7
313977    CA   M  1988  Franciscojavier     10

#### Ordenação usando o argumento `key`

In [58]:
babynames.sort_values('Name', key = lambda name : name.str.len(), ascending = False).head()

       State Sex  Year             Name  Count
316886    CA   M  1989  Franciscojavier      6
327472    CA   M  1993  Ryanchristopher      5
337477    CA   M  1997  Ryanchristopher      5
321792    CA   M  1991  Ryanchristopher      7
313977    CA   M  1988  Franciscojavier     10

### Ordenação usando a função `map`

In [59]:
babynames['dr_ea_count'] = babynames['Name'].map(lambda name : name.count('dr') + name.count('ea'))

babynames.sort_values(by = 'dr_ea_count', ascending = False).head()

       State Sex  Year      Name  Count  dr_ea_count
101976    CA   F  1986  Deandrea      6            3
115957    CA   F  1990  Deandrea      5            3
308131    CA   M  1985  Deandrea      6            3
131029    CA   F  1994  Leandrea      5            3
108731    CA   F  1988  Deandrea      5            3